### ISSUE TITLE
Wildhorn v2 (Rio) Release

### ISSUE THREAD

**Issue by jjperezaguinaga** [hoprnet/hopr-devrel#12]
### hoprnet/provider-proxy
- [x] https://github.com/hoprnet/provider-proxy/issues/1

### hoprnet/dev-ops
- [x] https://github.com/hoprnet/hopr-devops/issues/35

### hoprnet/hoprnet
- [x] https://github.com/hoprnet/hoprnet/issues/2498
- [x] https://github.com/hoprnet/hoprnet/issues/2499
- [x] https://github.com/hoprnet/hoprnet/issues/2500
- [x] https://github.com/hoprnet/hoprnet/issues/2526
- [x] #51 

###  community
- [x] #13
- [x] #45

**Comment by nionis** [comment]
we need to add an extra task in `hoprnet/hoprnet` list, see https://github.com/hoprnet/hoprnet/issues/2417#issuecomment-924937447

**Comment by jjperezaguinaga** [comment]
Moved leaderboard improvements to https://github.com/hoprnet/hopr-devrel/issues/57
