### ISSUE TITLE
Fulfil winning DAI proposal from DAO experiment v0.2

### ISSUE THREAD

**Issue by jayveq** [hoprnet/hopr-devrel#149]
## Issue deadline
Feb 11, 2022

## Detailed Description

~~As voted on in the DAO: https://forum.hoprnet.org/t/proposal-12-buyback-hopr-from-the-market-and-distribution-among-the-participants-of-the-staking-program/3280 we want to build a staking incentivization program for the second season of HOPR staking.~~

~~In implementing this proposal, we want to have a requirement for people to have staked in the second season to be able to receive a portion of the reward (of overall roughly 160,000 HOPR token).~~

~~All rewards should be proportional to the payout of the previous staking program (season 1).~~

The winning DAI proposal in the second HOPR DAO experiment (original proposal [here](https://forum.hoprnet.org/t/proposal-12-buyback-hopr-from-the-market-and-distribution-among-the-participants-of-the-staking-program/3280), interpretation by HOPR Association [here](https://medium.com/hoprnet/hopr-dao-fulfilment-34cea2b3d1b9)) stipulated that 67,505 DAI be used to buyback HOPR tokens from the market and distribute them as additional rewards to stakers.

Rewards should be distributed proportional to rewards earned between the time the address began staking and a chosen end point, to be used as a snapshot. 

The snapshot will be taken during Season 2 of the staking program, so rewards accrued across both seasons up to the snapshot are counted.

Only addresses staking at least 100 HOPR in Season 2 at the time of the snapshot are eligible.

Addresses which only participated in Season 2 of the staking program only are eligible.

### Calculating rewards

- [x] Select cut-off time for snapshot
- [ ] Create Dune query that outputs all eligible addresses and reward amounts (two arrays)

### Acquiring and distributing rewards

- [ ] #196
- [x] Withdraw DAI from Uniswap Pool
- [x] Buyback HOPR from market with correct amount of DAI
- [x] Transfer HOPR to HOPR Association multisig
- [ ] Bridge HOPR amount to Gnosis Chain
- [x] Transfer Ownership of HOPR Distributor on Gnosis Chain from legacy Gnosis Wallet to new Gnosis Safe
- [ ] Add new schedule `DAO v0.2 rewards` with a single payout at least three months after snapshot
- [ ] Add allocations from Dune query to schedule

## Definition of Done

Allocations have been added to the HOPR Distributor on Gnosis Chain.

**Comment by Eleonora0119** [comment]
Issue 2. 
Query to output the eligible addresses and rewards amounts: https://dune.xyz/queries/389196

**Comment by QYuQianchen** [comment]
1. `stake_season1` should have an additional filter for `WHERE stake_s1 > 0`
2. What you calculated in `rewards` table considers only the "claimed" rewards per account over the total "claimed" rewards of all the stakers. Stakers may be entitled for more rewards but haven't claim, so the proportion is not right.
3. Why did you do `LEFT JOIN` in merged_season? Shouldn't `INNER JOIN` be sufficient?
4. After doing the `INNER JOIN` in point 3, you don't need to `COALESCE(proportion_to_rewards_s1, 0)`. Those `0` will only increase gas cost but transfer `0` token.

**Comment by Eleonora0119** [comment]
Requested modifications are made new query: https://dune.xyz/queries/390107
Remaining questions:
- Left or inner join in the merged_season (in case of an inner join, the query does not include the accounts, which are new in the staking program)

**Comment by thewanderingeditor** [comment]
Accounts which are new to the staking program should also be included

**Comment by QYuQianchen** [comment]
I checked the query again. It seems like all the accounts are included. Which accounts do you refer to exactly? 
> Accounts which are new to the staking program should also be included

Also, our whitehat hack for S1 does not affect the result.

**Comment by Eleonora0119** [comment]
The accounts, which didn't stake in season1, but started to stake in season2

**Comment by QYuQianchen** [comment]
What's their amount then? If they were not in season 1, their award is 0.

**Comment by Eleonora0119** [comment]
Exactly! If you want don't want to give any reward for joining the staking program, it works perfectly.

**Comment by QYuQianchen** [comment]
Query that appends new comers https://dune.xyz/queries/569765
Assign 0 as "proportion to total rewards in s1" to those new comers.

For those eligible accounts (see definition in the ticket description above) that have something as stake in season 1, their rewards correspond to 39.15 % of the total rewards in season 1.

**Comment by thewanderingeditor** [comment]
Updated based on my understanding of the DAO proposal. Will confirm with @SCBuergel which tasks have already been completed

**Comment by thewanderingeditor** [comment]
Snapshot selected as 2pm CET on February 17th

**Comment by QYuQianchen** [comment]
> Query that appends new comers https://dune.xyz/queries/569765 Assign 0 as "proportion to total rewards in s1" to those new comers.
> 
> For those eligible accounts (see definition in the ticket description above) that have something as stake in season 1, their rewards correspond to 39.15 % of the total rewards in season 1.

I've adapted the query. Please have a quick check on the result
