### ISSUE TITLE
Staking season 2 unlock

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-devrel#163]
The contract used for season 2 includes the same claim/unlock bug which was experienced after end the of season 1:

Contract: https://blockscout.com/xdai/mainnet/address/0x2cDD13ddB0346E0F620C8E5826Da5d7230341c6E/transactions
Bug: https://github.com/hoprnet/hopr-stake/issues/42

The fix was to drain rewards prior to the end of the staking program and use an interfacing contract to prevent stakers to get dead-locked.

Bug-fix PR: https://github.com/hoprnet/hopr-stake/pull/43

The same procedure must be set up and put in place before the end of season 2.

# Tasks

- [ ] Drain rewards from season 2 staking contract before program end
- [ ] Set up `HoprWhitehat` for season 2
- [ ] Update website to perform unlock function through `HoprWhitehatV2` contract instead of directly on `HoprStake2`
- [ ] Update website to not show `claim` and `sync` buttons after program end

# Definition of Done

- [ ] A staker cannot use the `HoprStake2` unlock function after program end
- [ ] A staker cannot use the `HoprStake2` claim function after program end
- [ ] The website only shows the unlock button after program end
- [ ] The website uses the `HoprWhitehat2` contract for unlocking funds

**Comment by QYuQianchen** [comment]
We also need to run a check on the _accounts that redeemed NFTs but nothing at stake_. Their NFTs would be unlocked forever. The only way to unlock their NFT is to ask **them** to stake a little bit of xHOPR

**Comment by tolbrino** [comment]
Closing, since the website will be updated as part of #207
