### ISSUE TITLE
ETH Denver prep: Review tutorials & docs

### ISSUE THREAD

**Issue by SCBuergel** [hoprnet/hopr-devrel#171]
### Issue deadline
February 11

### Detailed Description
@QYuQianchen & @NumberFour8 will be on-site supporters for hacker at ETH Denver. In order to prepare for that, they need to review tutorials & docs so that they know where to point hackers and how to support them.

### Definition of Done
Both hackathon supporters need to:
- [x] Be familiar with all tutorials and docs
- [x] Have built a simple hello-world dApp on top of HOPR
- [x] Be able to deliver a conversational 30s pitch to hackers at ETH Denver
- [x] Description of our payment channel topology in docs, including relevant events. Additionally summarize the importance score of each node.

### Docs & Tutorials
See https://github.com/hoprnet/hopr-devrel/issues/166

**Comment by jjperezaguinaga** [comment]
Please see https://docs-hoprnet-org-git-jjpa-docs-hopr-cluster-170-hoprnet.vercel.app/ as the latest documentation update as of time of writing.

**Comment by NumberFour8** [comment]
- GitPod Hello World setup on `master` and `release/lisbon` branches
- documentation updated and massively improved (thanks to @jjperezaguinaga )
- payment channel description docs updated by @QYuQianchen
