### ISSUE TITLE
DAO experiment v0.3

### ISSUE THREAD

**Issue by jayveq** [hoprnet/hopr-devrel#197]
The third DAO experiment will start 8th March and run for around two weeks. The goal is to ask the community for ideas for dApps to be built on top of HOPR. The community will then vote on its favourite. The participants who proposed the winning ideas will receive a prize, but there will be no commitment to actually develop them. Prizes will be allocated by token holders via a DAO vote on snapshot, and a separate prize will be awarded by the tech team / HOPR Association.

This experiment will mostly be handled by the comm team, but some input will be required from tech during most phases.

# Tasks

### Phase 0: Preparation

- [x] @thewanderingeditor and @Eleonora0119 discuss potential updates and improvements to DAO processes on Discourse forum. **Deadline:** March 5th

### Phase 1: Discussion

- [x] Tech team provide support to moderators in assessing proposal validity, and generally participating in the conversation to boost community morale. **Timeline:** The discussion will run for a week, probably from March 8th - 15th.

The procedure for assisting with validation is as follows: 

Proposals which need moderation are tagged with the [proposal-pending](https://forum.hoprnet.org/tags/c/hopr-dao-v0-3/67/proposal-pending) tag. 

- If a proposal is viable to be built on top of HOPR, change the tag to proposal-valid. 
- If a proposal cannot be built on top of HOPR, change it to proposal-invalid. Feel free to add an explanation if you think it would benefit the discussion in general.
- If you can see that it might be viable to build, but would require more information, explain what you'd need to see and change the tag to proposal-incomplete. Or ping @thewanderingeditor

### Phase 2: Referendum

No tech input required

### Phase 3: Vote

- [x] Update the snapshot strategy to include staking v2 instead of v1 @QYuQianchen **Deadline:** March 15th

### Phase 4: Rewards calculation and distribution

- [x] #202 **Deadline** March 21st
- [x] Calculate participation scores using Discourse data plugins @QYuQianchen **Deadline:** March 25th
- [x] #203 **Deadline:** March 25th
- [x] Distribute NFTs and HOPR token prizes to winners and participants **Deadline:** March 29th

**Comment by thewanderingeditor** [comment]
Clarifications:

The third DAO experiment will start 7th March and run into the week of 14th March. The goal is to ask the community for ideas for dApps to be built on top of HOPR. The community will then vote on its favourite. The participants who proposed the winning ideas will receive a prize, but there will be no commitment to actually develop them.

The experiment will follow the standard DAO procedure: 

- a discussion on the forum to produce valid proposals
- a referendum on these proposals to determine which will go to vote
- a vote on Snapshot where HOPR token holders can determine the winner

Based on previous experiments, for this to produce useful results, some input from tech will be required.

In the discussion phase, the moderators will require some input from tech to ensure that the community has enough information to produce feasible suggestions. This would ideally take the form of active participation in the discussion, as this is something the community really appreciates, but at a minimum it would be useful for someone for tech to look over the pending proposals to determine if they're feasible.

For the vote, the snapshot strategy will need to be updated to consider the stake v2 contract instead of stake v1.

Parallel to the community vote, the HOPR Association will also issue an award for its favourite idea. Tech's input would be valuable in making that decision.

Finally, it would be useful to coordinate with @Eleonora0119 to see if there are any improvements to the overall forum process which could be implemented quickly.

**Comment by Eleonora0119** [comment]
Takeaways for the DAO v02 evaluation:

TECHNICAL

Very important to keep the tagging systematic and traceable, especially the ones which are counted multiple times in the evaluation (e.g. not only the proposal counts but also the signature)

Better to add more tags, than to remove any – helps to refine the query

Last time the problematic categories were:
-	Referendum stage proposal
-	Valid non-referendum proposal with 3+ signatures

Minimizing the redundancy, duplication – idealistic (maybe unrealistic) one proposal one post
Encouraging discussion on the post which is “official”
Creating „signature” function
The employee of HOPR a) should have an admin right, b) another tag, that can be filtered out


STRUCTURE OF EVALUATION

The threshold to “referendum stage proposals is probably low, which causes the issue that there are fewer “valid, non-referendum stage proposals” than “referendum stage, non-winning ones” – hence they are better paid

Participants doesn’t like to “like” each other’s post, which makes the “3 post 3 likes rule” hard to achieve (had to be changed in the DAO v02 evaluation to 3 posts 2 likes – otherwise only 1 person would have qualified)

It would be worth tracking/defining the rule of “moderator power”

+ one:
Asking for updating NFT addresses in advance

**Comment by thewanderingeditor** [comment]
Issue #202  has been added to this epic

**Comment by QYuQianchen** [comment]
Draft strategy created at https://github.com/hoprnet/snapshot-strategies/tree/hopr-staking-v2 and waiting for syncing https://thegraph.com/hosted-service/subgraph/hoprnet/staking-season2?version=pending

To do:
1. Wait for a full sync of the subgraph
2. run a successful `yarn test`
3. make pr to snapshot-strategies repo
4. follow up till it gets merged

**Comment by nionis** [comment]
@Eleonora0119 @QYuQianchen @thewanderingeditor can we update the progress on this epic?

**Comment by thewanderingeditor** [comment]
I believe that's now accurate. Three tasks still to complete

**Comment by SCBuergel** [comment]
Un-assigned Nora as her internship ends today and assigend @QYuQianchen to
- [ ] Calculate participation scores using Discourse data plugins @QYuQianchen **Deadline:** March 25th

**Comment by Eleonora0119** [comment]
The evaluation is available: https://github.com/hoprnet/hopr-devrel/blob/main/analytics/dao_v03/dao_v03_evaluation.ipynb

For @QYuQianchen tasks remained:
- changing the FORUM CSV files to new ones - checking the final amount
- modifying the m_m user_ids, and the calculation of the 5% share, based on the number of rewarded participants
`m_m = pd.DataFrame({'user_id': [603, 594, 1307, 810], 'm_m': [0.05/4, 0.05/4, 0.05/4, 0.05/4]}).reset_index(drop=True)`
- remowing duplications at the end of the code

**Comment by tolbrino** [comment]
Data has been provided to @thewanderingeditor . Please take over.

**Comment by thewanderingeditor** [comment]
NFTs minted and distributed. This issue is now closed.
