### ISSUE TITLE
Update HOPR Staking Contract for Seasons 3 and 4

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#205]
### Issue deadline

April 19th

### Detailed Description

This is part of #207 

The HOPR staking program will move from Season 2 to Season 3 at 2pm CET on April 26th. To prepare for this change, the staking contract will need to be updated and redeployed.

The following changes need to be made:

### Required Changes

- [x] New start and end dates
- [x] Fix to the bug which caused some tokens to be locked at the end of Season 1: https://github.com/hoprnet/hopr-stake/issues/51
- [x] Update how certain NFT types are handled to match the results of the NFT audit (#213)
- [x] Update base APR and Boost Cap values, depending on the results of the NFT audit (#213)

### Possible Changes

- [ ] New rules to mitigate issues surrounding the new Developer NFT which grants immediate access to the whitelist

UPDATE: It was also decided that we would prepare and deploy the Season 4 contract at this time. 

### Parameters for Seasons 3 and 4 

| Parameter | Season 3 | Season 4 |
| ---- | ---- | ---- |
| Start Date* | April 26th | July 26th |
| End Date* | July 26th | October 26th |
| Base APR | 10% | 10% |
| Boost Cap | 150k | 150k |
| Ignored NFTs | HODLr | HODLr + S1** |

*All times are 2pm CET
** The S1 ranks are `DAO_v2, Surveyor, Wildhorn_v1, Wildhorn_v2, PuzzleHunt_v1, PuzzleHunt_v2`

**Comment by thewanderingeditor** [comment]
Start and end dates set as 26th April 2pm CET - 26th July 2pm CET

Boost cap to be reduced from 1m to 100k

Base APR to be reduced to 10%

**Comment by QYuQianchen** [comment]
Could you please update parameters for S4?

**Comment by thewanderingeditor** [comment]
> Could you please update parameters for S4? @thewanderingeditor

Updated in issue

**Comment by QYuQianchen** [comment]
BTW, "Wildhorn v2" appeared twice: `Wildhorn_v2` and `Wildhorn v2`

> ** The S1 ranks are DAO_v2, Surveyor, Wildhorn_v2, Wildhorn v2, PuzzleHunt_v1, PuzzleHunt_v2

**Comment by thewanderingeditor** [comment]
> BTW, "Wildhorn v2" appeared twice: `Wildhorn_v2` and `Wildhorn v2`
> 
> > ** The S1 ranks are DAO_v2, Surveyor, Wildhorn_v2, Wildhorn v2, PuzzleHunt_v1, PuzzleHunt_v2

Thanks. Should have been both v1 and v2. Updated in issue

**Comment by QYuQianchen** [comment]
Note that, to simplify SC work, the blocklist would affect NFT redemption in such a way:
1. Before an NFT type gets blocked, stakers can stake those NFTs and get a booster in APY;
2. After an NFT type gets blocked, no more NFT of the blocked type can be redeemed (tx will be reverted), and thus no new booster from blocked NFTs. However the previously redeemed NFTs will still be affective, so stakers who did step 1 will still benefit from the boosted APY.
3. If the blocked NFT type gets "unblocked" (allowed), then those NFTs can be redeemed again.

**Comment by QYuQianchen** [comment]
RE "Dev NFT", see [discussion thread](https://github.com/hoprnet/hoprnet/issues/3182#issuecomment-1082557678), we have decided on issuing "0% APY" HoprBoost NFT to devs. Devs can then stake those NFTs in the latest staking season.
[`NetworkRegistryProxy`](https://github.com/hoprnet/hoprnet/blob/whitelist/packages/ethereum/contracts/proxy/HoprStakingProxyForNetworkRegistry.sol) will be updated to always treat "Dev NFT" type as "eligible" tokens. Devs (Ethereum accounts that hold "Dev" NFTs) can then call `selfRegister(string HoprNode)` by providing the multiaddress of their node to the `HoprNetworkRegistry` smart contract. Upon successful registration, hopr-core will allow connection to those nodes.
