### ISSUE TITLE
Transition from HOPR Staking Season 2 to Season 3

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#207]
### Deadline

Staking Season 3 begins at 2pm CET on April 26th. We should be ready to go at least 24hrs in advance. Individual subtasks will have even earlier deadlines.

### Description

The second season of the HOPR staking program ends at 2pm CET on April 26th. Season 3 will launch as soon as Season 2 ends. We need to be prepared for this transition. Many of the tasks duplicate those from the Season 1 to Season 2 transition (covered in #138), as most of the features of Season 2 will persist into Season 3.

However, some changes are necessary due to the bug in the staking contract, the need to audit the NFT program, and possible complications arising from the Developer NFT.

### Tasks

- [x] Decide when Season 3 will end and determine precise parameters of NFT audit **Deadline: March 28th**
~~- [x] #204 **Deadline: April 5th**~~
- [x] Audit the NFT program #213  **Deadline: April 6th**
- [x] Determine the nature of the Developer NFT and whether this affects the staking contract and / or staking website **Deadline: April 7th**
- [x] #205 **Deadline: April 26th**
- [x] #206 (which includes #163) **Deadline: April 26th**
- [x] Reach out to whale accounts to drain staking pool ahead of end
- [x] Top up staking rewards right after the program ends
- [x] #222 

##### Optional Tasks

- [x] #214
- [x] #215
- [x] https://github.com/hoprnet/hopr-devrel/issues/228

## Definition of Done
Staking transition is completed on time and with the abovementioned features

**Comment by nionis** [comment]
after our priority discussion, @SCBuergel will sync with @thewanderingeditor on a different approach for #204, this epic will not be part of the upcoming sprint

**Comment by thewanderingeditor** [comment]
After syncing with @SCBuergel, a new approach to the audit was agreed. I've updated the epic to reflect this, and added #213

**Comment by thewanderingeditor** [comment]
It was decided the third season would end after three months, on Tuesday July 26th at 2pm CET

**Comment by tolbrino** [comment]
@thewanderingeditor @Jaguaras The tech work has been completed. Please take over and handle the open steps or close the epic.

cc @nionis @QYuQianchen

**Comment by thewanderingeditor** [comment]
Finished and closed
