### ISSUE TITLE
NFT Program Cost Audit

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#213]
This is not a request for tech work, just an issue to track progress on the NFT Audit required for #207.

### Deadline

April 6th

### Description

As we move into Staking Season 3 and beyond, we need to conduct an analysis and cost audit of the NFT program, which was originally conceived as a short-term stopgap before the launch of cover traffic rewards. This will primarily be conducted by @thewanderingeditor.

We need to assess:

- The overall cost of the staking program
- The overall cost of the NFTs by season
- The relative costs of particular types of NFTs
- The NFTs held by the largest stakers, and how and when they acquired them

This will allow us to define the budget for issuing new NFTs and determine whether certain NFTs should be discontinued, or whether we should reduce the cap on boostable token balance (currently set at 1m).

### Tasks

Use the existing Dune queries to assess the NFT impact of:

- [x] The top 20 accounts by total HOPR staked
- [x] ~~The top 20 accounts by number of NFTs staked~~ (Hard to assess and less useful than expected)
- [x] The top 20 accounts by combined boost amount

Assess the cost savings of:

- [x] Reducing the cap on boostable stake from 1m to 500k and 250k HOPR tokens
- [x] Reducing the base APR
- [x] Eliminating the first season of NFTs
- [x] ~~Switching to a limited reward pool to better emulate cover traffic~~ (We decided this was infeasible so doesn't need to be modelled yet)

In addition, generate archetypes of particular users (whales, active small stakers, etc.) and model the impact of the above changes on a typical staking position, particularly the switch to a limited reward pool.

**Comment by thewanderingeditor** [comment]
Updated tasks and expanded account checks from top 10 to top 15 based on internal conversations and the recent staking of three very high amounts.

**Comment by thewanderingeditor** [comment]
Based on initial analysis, further expanded account check from 15 to 20 and added checks for top account by combined boost amount, which isn't necessarily equivalent to most NFTs and may help identify particularly costly NFT types

**Comment by thewanderingeditor** [comment]
Initial findings [here](https://docs.google.com/spreadsheets/d/1vcv_I1E3neY3Y1jEV9H25Np7YgZNXms0-hm1UX1D06I/edit#gid=1098414408). Moving on to participant archetypes.

**Comment by thewanderingeditor** [comment]
Modeled 12 common archetypes and [created tool](https://docs.google.com/spreadsheets/d/1vcv_I1E3neY3Y1jEV9H25Np7YgZNXms0-hm1UX1D06I/edit#gid=1782785535) to compare effects of adjusting boost cap, stake and NFT inclusion on various staking profiles

**Comment by SCBuergel** [comment]
@thewanderingeditor if this issue is done (I see one open task above) pls close the issue here

**Comment by thewanderingeditor** [comment]
Proposed changes: 

Start and end dates set as 26th April 2pm CET - 26th July 2pm CET

Boost cap to be reduced from 1m to 100k

Base APR to be reduced to 10%

HODLr NFTs to be ignored
