### ISSUE TITLE
[DRAFT] Analyze current staking participation and model the effects of changing to a CT-like budgeted allocation

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#245]
### Description

Our current staking setup rewards participants with a variable APR based on their stake amount and the number of HOPR Boost NFTs they stake.

Eventually, HOPR will move away from this to an incentive scheme based on cover traffic, where a set amount of tokens will be distributed proportionally amongst all holders.

We're interested in modelling how transitioning to an intermediate system will affect different types of staker.

### Tasks

- [ ] Analyze the current stakers and divide them into different "archetypes", [based on this model from the earlier audit](https://docs.google.com/spreadsheets/d/1vcv_I1E3neY3Y1jEV9H25Np7YgZNXms0-hm1UX1D06I/edit#gid=1098414408).

- [ ] Calculate how many stakers fall into each archetype, and what proportion of rewards each archetype receives

- [ ] Analyze the frequency and amount of restaking for each archetype

- [ ] Model how rewards change when switching to a budget-based system (assuming the transition is instantaneous, i.e., everyone stakes their current amount immediately, with no first-mover advantage)
