### ISSUE TITLE
Transition from HOPR Staking Season 3 to Season 4

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#250]
### Deadline

Staking Season 4 begins at 2pm CET on July 27th. We should be ready to go at least 24hrs in advance. Individual subtasks will have even earlier deadlines.

### Description

The third season of the HOPR staking program ends at 2pm CET on July 26th. Season 4 will launch as soon as Season 3 ends. We need to be prepared for this transition. Many of the tasks duplicate those from the Season 2 to Season 3 transition (covered in #138), as most of the features of Season 3 will persist into Season 4.

We need to ensure the new website is live, the staking smart contracts are deployed and the NFT blacklist is updated.

### Tasks

- [x] Determine when Season 4 will end and whether base rate and boost cap should change **Deadline: July 15th**
- [x] Complete second phase on NFT Audit  **Deadline: July 8th**
- [x] Create and deploy Season 4 smart contracts **Deadline: July 25th**
- [x] Create and deploy Season 4 website **Deadline: July 25th**
- [x] Update NFT blacklist **Deadline: July 25th**

## Definition of Done
Staking transition is completed on time and with the abovementioned features

**Comment by thewanderingeditor** [comment]
Completed and closed
