### ISSUE TITLE
hopr-sdk v1

### ISSUE THREAD

**Issue by mjadach-iv** [hoprnet/hopr-devrel#267]
### Description

The objective for HOPR SDK version 1 is to create a library that both _internal developers_ and _external developers_ can leverage in order to reduce code duplication and increase development speed.

At the same time, it's important to note that the _version 1_ of the SDK focuses mostly on _frontend_ / _dapp_ development rather than _backend_ development. Additionally, the `com-tech` team will be maintaining the library, so keeping it very simple at the moment is very important.

The plan is to ship everything under one package `@hoprnet/sdk` but separate within the library the 2 components we have identified are most relevant for frontend developers.

1. `@hoprnet/sdk`: will contain standard utility functions that are framework agnostic (potentially also usable in a backend environment)
2. `@hoprnet/sdk/react`: will contain a few hooks and components that should make life easier for react developers

While we would like to support `web-components` instead of `react`, we decided to support that in upcoming versions of `hopr-sdk`.

### Relevant issues

- [ ] initial repository setup & tooling for creating a package
- [ ] implement agnostic tooling
  - types typescript (suggested source: https://github.com/hoprnet/hoprnet)
  - API  (suggested source: https://github.com/hoprnet/hoprnet/hopr-admin)
  - sign requests 
  - getUrlParams (suggested source: https://github.com/hoprnet/hoprnet/hopr-admin)
  - LOGO (svg and png)
- [ ] implement react sub-package
  - react-hopr
  - useWebsocket hook
  - component: powered by HOPR
- [ ] implement unit tests
- [ ] add documentation

### Definition of DONE

Package `@hoprnet/sdk` version `>=1.0.0` has been published.

**Comment by mjadach-iv** [comment]
SDK was created: https://github.com/hoprnet/hopr-sdk
