### ISSUE TITLE
HOPR Admin v3

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-devrel#273]
### Description

`hopr-admin` has been part of the HOPR protocol [codebase](https://github.com/hoprnet/hoprnet/tree/master/packages/hoprd/hopr-admin) since its inception.
We have since then, taken steps to decouple it so it can be its own standalone dApp.

- v1: tightly coupled with the backend, using API v1
- v2: decoupled from the backend, using API v2

For v3, we would like to do the following:

- move `hopr-admin` project into a new repository within the `hoprnet` organization (similar to myne-chat)

#### tech
- move `hopr-admin` to a new repository

#### comm
- update docs

The following tasks can be done in parallel. Furthermore, the HOPR Admin v3 can be tested on Playground _before_ it gets shipped by HOPRd by default.

### Definition of DONE

- [x] hopr-admin is deployed at `https://admin.hoprnet.org`
- [x] hopr-admin is managed in its own repository
- [x] hopr-admin has been removed from CORE monorepo
- [x] hopr-admin has basic CI setup including deployment
- [x] hopr-admin available on DappNode
- [x] hopr-admin available on Avado

**Comment by tolbrino** [comment]
All relevant changes were made. Any docs updates or further HOPR improvement are going to be performed outside of this scope.
