### ISSUE TITLE
Automate Network Registry Dashboard deployment

### ISSUE THREAD

**Issue by ausias-armesto** [hoprnet/hopr-devrel#282]
### Issue deadline
NONE

### Detailed Description
The goal of this epic is to create the automation process for helping building and deploying the new service `network-registry-dashboard` in hopr infrastructure.

### Tasks

- [ ] Create a github action to build and publish on GCP the docker image on every push to master.
- [ ] Restrict changes directly to branch master and only through a PR
- [ ] Create ansible playbook to install a MySQL server
- [ ] Create ansible playbook to install network-registry-sync. This playbook will create:
       - Create Mysql user and schema
       - Install a docker-compose with the docker image and fluentbit
       - Create the cron job 
- [ ] The github action shall force the update of the image on the server and the restart of the service
- [ ] Create a linux service so it is always up and running

### Definition of done

- [ ] PR are approved and merged
- [ ] On every push to master the changes are deployed immediately to the server.
