### ISSUE TITLE
Implement HOPR RPC Relay

### ISSUE THREAD

**Issue by nionis** [hoprnet/hopr-devrel#284]
### Issue deadline

28/09/2022

### Detailed Description

Build HOPR RPC Relay

HOPR RPC Relay is a nodejs-powered instance which interacts with HOPRd via the API.
This project aims to act as an RPC node that sends traffic into the HOPR network and then relays requests to an RPC provider.

Example of the message flow:
```
Wallet -> (entry) HOPR RCP Relay -> HOPRd (auto path) -> (exit) HOPR RPC Relay -> Provider
```

Example of message construction:
```
`rpcrelay:req:1:4:REQ_BODY` = `APP_ID:MSG_TYPE:SEGMENT_NR:NR_OF_SEGMENTS:REQ_BODY`
```

This project is split between 2 areas:

1. entry
A wallet adds support to include the HOPR RPC Relay endpoint. All wallet rpc requests are going through HOPR RPC Relay.
HOPR RPC Relay then needs to send that message to a destination node which also runs HOPR RPC Relay.
To ensure the delivery of the message, we will need to build a naive segmentation functionality.

2. exit
Once it receives a HOPR RPC Relay message, the exit node will relay that message to a given RCP provider.
When the response is back, HOPR RPC Relay sends the response back to the sender.

### Tasks

- [x] implement a dummy version of the HOPR RPC Relay instance (https://github.com/hoprnet/hopr-rpc-relay)
- [x] create dockerfile, docker-compose, Pluto style RPC relay
- [x] finalize HOPR RPC Relay instance
- [x] test
- [x] documentation
  - project README
  - bogota guide
  - bogota video

**Comment by tolbrino** [comment]
This has been completed and used.
