### ISSUE TITLE
Transition from Staking Season 4 to Season 5

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#285]
### Issue Deadline

The Staking Season switch is at 2pm CET on October 26th (but various team holidays may mean work should be completed sooner)

### Detailed Description

Like before (#250, #207), we need to prepare to transition to the next staking season. This requires auditing the current season, potentially updating the core staking parameters (base rate, boost cap, end date), updating and deploying the new smart contract and updating the website at stake.hoprnet.org

The transition will also impact network registry and testing, but this should be handled in a separate epic.

### Tasks

- [x] Audit staking season 4 (next possible audit is in 2023)
- [x] Update NFT blacklist 
- [x] Set parameters: boost rate, boost cap, end date
- [x] Check which address should be the owner
- [x] Update staking smart contract with parameters
- [x] #291
- [x] #292
- [x] #287
- [x] #286
- [x] #288
- [x] Create a Dune dashboard

**Comment by tolbrino** [comment]
@QYuQianchen please close this epic when #288 is done.

**Comment by QYuQianchen** [comment]
Closing this epic as the first sync was done on Monday
