### ISSUE TITLE
Deploy subgraphs on decentralised Graph network

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-devrel#298]
This replaces the subgraphs on the hosted network.

We are looking to re-deploy all relevant subgraphs which are in active use. Older subgraphs (for older staking seasons) won't be migrated since these are not used anymore anyway.

### Definition of Done

- Ethereum Mainnet Subgraphs
  - [x] HOPR on mainnet
- Gnosis Chain Mainnet Subgraphs (planned for mid January 2023, waiting for Gnosis network support)
  - [x] Staking Season 4
  - [x] Staking Season 5
  - [ ] Staking Season 5 development (Goerli)
  - [x] Staking Season 6
  - [x] Staking Season 6 development
  - [x] HOPR Channels (Monte Rosa)
  - [x] HOPR on xdai

**Comment by QYuQianchen** [comment]
Old staking subgraphs are still used by their respective frontends, e.g. https://stake-s3.hoprnet.org/ 
Will the hosted service be sunset soon?

**Comment by QYuQianchen** [comment]
Migration guide: https://thegraph.com/blog/how-to-migrate-ethereum-subgraph/

**Comment by QYuQianchen** [comment]
Blocked at the final step: confirm 2 multisig transactions. Once the 1st gets confirmed, initiate the 2nd one at https://thegraph.com/studio/subgraph/hopr-token-on-mainnet/playground/

**Comment by QYuQianchen** [comment]
2nd transaction was initiated today

**Comment by QYuQianchen** [comment]
Migration of the mainnet subgraph was completed on Monday. Working on the Gnosis chain ones

**Comment by QYuQianchen** [comment]
Changes for mainnet token subgraph migration:
- HOPR token on mainnet (https://github.com/hoprnet/hopr-community/pull/194)
Changes for Gnosis subgraph migration:
- HOPR Channels (https://github.com/hoprnet/hopr-community/pull/193)
- Staking seasons 4-6 and xHOPR/wxHOPR (https://github.com/hoprnet/hopr-devrel/pull/319)

**Comment by QYuQianchen** [comment]
Subgraphs are published under:

- HOPR Channels: https://thegraph.com/explorer/subgraphs/Feg6Jero3aQzesVYuqk253NNLyNAZZppbDPKFYEGJ1Hj?view=Overview&chain=mainnet
- Stake S6: https://thegraph.com/explorer/subgraphs/C7cu6NvvMxgjdaK9pKSGezZ3EgRCmM4tWrmTtGUDG15t?view=Overview&chain=mainnet
- Stake S6 (development): https://thegraph.com/explorer/subgraphs/4WJnFMjWvM6MBw645wfwBkznwnJwMZqTmtUUZXp2DeG1?view=Overview&chain=mainnet
- Stake S5: https://thegraph.com/explorer/subgraphs/Fh6rd5cEsANePqskghiZ88ESUp1JXQ56e8w5asuVRHfz?view=Overview&chain=mainnet
- Stake S4: https://thegraph.com/explorer/subgraphs/DvbAnNwqwtFcVmzDWz1wVoCjnKevAyFp7XZEGuReib6X?view=Overview&chain=mainnet
- HOPR on Gnosis: https://thegraph.com/explorer/subgraphs/njToE7kpetd3P9sJdYQPSq6yQjBs7w9DahQpBj6WAoD?view=Overview&chain=mainnet
- HOPR token on mainnet: https://thegraph.com/explorer/subgraphs/5GJcMEW1uKvE9CRddN6yg8qbPnsGuB5dg4wA1UTEQv5W?view=Overview&chain=mainnet
