### ISSUE TITLE
Update network.hoprnet.org in preparation for Season 6 rewards

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#315]
As part of Staking Season 6, tokens will be awarded to network participants registered via the community NFT, on a bi-weekly basis. The exact parameters will change from period to period, but at least at first the uptime metrics measured by pingbot will be used. 

### Issue deadline

February 1st 2023

### Tasks

- [x] Define the equation used to calculate rewards for each user each period
- [x] Modify the pingbot database to create an "airdrop" list every two weeks which contains the rewards for each address in a format which Comm team can use to batch stake the rewards via the modified Season 6 staking contract
- [x] Update network.hoprnet.org and / or stake.hoprnet.org to show users their expected rewards for each period
- [x] Define the budget for each period

**Comment by thewanderingeditor** [comment]
Closed as completed
