### ISSUE TITLE
Staking Season 6 Transition

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#317]
Season 5 of the HOPR staking season ends on 26th January 2023 at 2pm CEST. The sixth HOPR staking season is due to start immediately afterwards. In order to ensure a smooth transition, various tasks need to be completed, mostly related to the staking smart contract and the staking website.

### Changes from previous seasons

In addition to the usual parameter and NFT changes, there are some alterations planned for Season 6. First, the staking website will be update to use the subgraph more, rather than relying on many RPC calls.

Second, Season 6 includes a new type of reward: HOPR tokens airdropped to staking addresses, directly as stake. To achieve this, the staking contract needs to be modified to allow an address (the comm safe) to stake on behalf of other addresses.

Adjustments also need to be made to network.hoprnet.org to ensure the data needed for these airdrops is readily available.

### Detailed Description

The following tasks and issues form part of this epic:

- [x] Update NFT block list 
- [x] Set parameters: boost rate, boost cap, end date
- [x] https://github.com/hoprnet/hoprnet/issues/4461
- [x] #311 
- [x] #312
- [x] #313
- [x] #314
- [x] #315
- [x] #316

### Deadline

The staking season has a hard deadline of 2pm CET on January 26th. Most tasks should be completed in the week before, but some can only be completed shortly afterward or are not as urgent. Individual issues have their own provided deadlines

**Comment by thewanderingeditor** [comment]
Closed as completed (#316 is transferred to Season 7)
