### ISSUE TITLE
Create Dune Dashboard and the Community Nodes filter

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/hopr-devrel#339]
### Tasks

- [x] Deploy the SC for SS8 on Dune
- [x] Create the Dune Dashboard for Staking Season 8 
- [x] Create the Communty nodes filter on Dune so that pingbot can distinguish community run nodes from other nodes

**Comment by MartinBenediktBusch** [comment]
Dune contracct deployment: https://dune.com/settings/contracts

**Comment by MartinBenediktBusch** [comment]
Community Node Filter: https://dune.com/queries/2769573
Season 8 Dashboard: https://dune.com/hopr/staking-season-8
