### ISSUE TITLE
Improve Distributor Dashboard 

### ISSUE THREAD

**Issue by MartinBenediktBusch** [hoprnet/hopr-devrel#347]
We have the following Dune Dashboard: https://dune.com/hopr/HOPR-Token-Allocation-Through-Distributor 

The dashboard visualizes the token distributed through our distributor smart contract. Add modify the following in the Dashboard: 

- [x] Add a simple overview table of all existing schedules (the current one lists all unlock times as well. It should just be schedule name, number of unlocks, time of first unlock)

add the following overview numbers:

- [x] already claimed
- [x] claimable right now
- [x] future claimable token (excluding the ones claimable now)
- [x] total allocations (equals the sum of the 3 above)
- [ ] table of claimable number of tokens per time interval, e.g. 09/2024: 123.45m HOPR, 02/2025: 25.333m HOPR, etc (the schedules always align around the same unlock time) (stale)

**Comment by jeandemeusy** [comment]
Closed as staled, and no additional requests.

**Comment by QYuQianchen** [comment]
Just corrected a few bugs in the query so all the wrong negative values are gone
