### ISSUE TITLE
DERP clone for DNS

### ISSUE THREAD

**Issue by tolbrino** [hoprnet/hopr-devrel#349]
Develop a clone of DERP which provides similar functionality but for DNS requests.

### Background

DERP makes RPC requests from a wallet transparent to the user and shows how the IP metadata and even HTTP metadata can be harvested. The same approach is useful to show users how simple DNS requests can be used to identify users.

### Name (Suggestion)

Hodor - Honest DNS Resolver

### Technical Approach (Suggestion)

- only support DNS over HTTPS
- requests are received, logged, "relayed" and the response sent back to the client
- developed and deployed as Cloudflare Worker

### Definition of Done

- [ ] system is deployed and accessible
- [ ] website is set up on a hoprnet.org subdomain
- [ ] usage is documented on the website
- [ ] usage is tested by team members
