### ISSUE TITLE
Update the current Snapshot strategy

### ISSUE THREAD

**Issue by thewanderingeditor** [hoprnet/hopr-devrel#353]
This is part of issue #351 

### Issue deadline

Based on current projections, the aim is to be able to hold a vote by January 22nd.

### Detailed Description

The current Snapshot strategy is outdated, since it is based on the old staking program. With the transition to SafeStaking, we need to update the strategy to correctly calculate tokenholders' balances for the purposes of governance. 

In addition, the transition to the new Community Trust governance processes on the Lexicon governance platform requires a further modification to the strategy, since vote power is no longer calculated purely quadratically.

Instead, it is calculated using the formula ` vote_power = token_balance ^ power_modifier `, where `power_modifier` can be set by the community to any value between 0 and 1, inclusive. Currently it is set at 0.75.

### Tasks

- [x] Spec out new Snapshot strategy
- [x] Code new Snapshot strategy
- [x] Test new Snapshot strategy
- [x] Submit strategy to Snapshot team for approval
- [x] Deploy new Snapshot strategy to the new HOPR Community Trust Snapshot space

**Comment by QYuQianchen** [comment]
Strategy "hopr-stake-and-balance-qv" can be included in the next DAO voting. Read more on how to set parameters https://github.com/snapshot-labs/snapshot-strategies/tree/master/src/strategies/hopr-stake-and-balance-qv
