### ISSUE TITLE
Remaining work on subgraph: migration and node running

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#364]
## Migration
Currently, the HOPR Association manages multiple subgraphs that index data from various blockchains, notably Ethereum Mainnet and the Gnosis chain. However, several subgraphs still reside on the hosted service, serving as fallback data sources for dApps and snapshot voting strategies.

The following subgraphs have not yet been migrated and published in the decentralized graph network:
- [HOPR staking program](https://thegraph.com/hosted-service/subgraph/hoprnet/hopr-staking-program) (for staking season 1)
- [HOPR staking season 2](https://thegraph.com/hosted-service/subgraph/hoprnet/staking-season2)
- [HOPR staking season 3](https://thegraph.com/hosted-service/subgraph/hoprnet/staking-season3)

Additionally, all the subgraphs deployed in the decentralized graph network should be migrated from Ethereum mainnet to Arbitrum in order to save costs on re-publishing upgrades:
- [HOPR Nodes Dufour](https://thegraph.com/explorer/subgraphs/FEQcaX9qfh31YL2K7rxRN5a3sr9rjMWkguJnby7StNRo?view=Overview&chain=mainnet)
- HOPR Nodes Rotsee
- [HOPR Stake all seasons](https://thegraph.com/explorer/subgraphs/DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY?view=Overview&chain=mainnet)
- HOPR on mainnet
- HOPR Channels 
- [HOPR on Gnosis](https://thegraph.com/explorer/subgraphs/njToE7kpetd3P9sJdYQPSq6yQjBs7w9DahQpBj6WAoD?view=Overview&chain=mainnet)
- [Staking Season 4](https://thegraph.com/explorer/subgraphs/DvbAnNwqwtFcVmzDWz1wVoCjnKevAyFp7XZEGuReib6X?view=Overview&chain=mainnet)
- Staking Season 5
- [Staking Season 6](https://thegraph.com/explorer/subgraphs/C7cu6NvvMxgjdaK9pKSGezZ3EgRCmM4tWrmTtGUDG15t?view=Overview&chain=mainnet)
 
Once migrated to Arbitrum, subgraphs' production query endpoints change to `https://gateway-arbitrum.network.thegraph.com/api/[api-key]/subgraphs/id/[subgraph-id]`

As CT and products use variouis subgraphs, we need to coordinate the update:
- [x] https://github.com/hoprnet/hopr-devrel/issues/367
- [x] Association initiate transactions on mainnet to upgrade all the subgraphs
- [x] CT app prepare PRs to update relevant subgraph endpoints. Consider using development endpoints as backup to reduce downtime during migration.
- [x] PRODs prepare PRs to update relevant subgraph endpoints. Consider using development endpoints as backup to reduce downtime during migration.
- [x] Association execute txns

## Node running
As staking dApps continue to allow staking accounts to claim rewards after seasons end, the respective subgraphs must actively feed data to these web applications. However, given the relatively low activity level and the decentralized subgraph's economic model, which does not naturally incentivize neutral indexers to index low-usage subgraphs, it's advisable for the association to run at least one graph node to index these subgraphs.

Moreover, heavily utilized subgraphs such as ["hopr-nodes-dufour"](https://thegraph.com/explorer/subgraphs/FEQcaX9qfh31YL2K7rxRN5a3sr9rjMWkguJnby7StNRo?view=Overview&chain=mainnet), "hopr-channels," and ["HOPR Stake all seasons"](https://thegraph.com/explorer/subgraphs/DrkbaCvNGVcNH1RghepLRy6NSHFi8Dmwp4T2LN3LqcjY?view=Overview&chain=mainnet) are vital for StakingHub and Cover traffic. Therefore, the HOPR Association should consider running a graph node for these subgraphs.
