### ISSUE TITLE
Leaderboard checklist & improvements

### ISSUE THREAD

**Issue by 0xjjpa** [hoprnet/hopr-devrel#57]
We have a few sets of tasks that need to be done every release, so we need to document the tasks that need to be done in the Leaderboard as well.

# Tasks

## Improvements
- [x] https://github.com/hoprnet/hopr-leaderboard/issues/96
- [x] #48

## Checklist
- [ ] #49
- [x] #47

## Documentation
- [x] #50
- [x] https://github.com/hoprnet/hopr-community/issues/104

## Node related
- [x] https://github.com/hoprnet/hoprnet/issues/2271

**Comment by jjperezaguinaga** [comment]
[grooming] For now no changes on this epic.

**Comment by jjperezaguinaga** [comment]
Quick update here, in general, I believe the Leaderboard should,

- Display an existing list of nodes connected and `announce`d on-chain per `HOPR_ENVIRONMENT`
- Run an authorized wallet so whitelisted users can get funds from it, whitelisting mechanism to be defined. Funds are obtained via our [API](https://github.com/hoprnet/api)
- Provide a profile version of aggregated data across versions to further usage using Ceramic (i.e. airdrops, whitelisting)
- Signature posting of `/sign`ed data used with the node, done on-chain instead of via Ceramic
- Remove all concept of app-key via Ceramic and instead focus on profile enhancement via Ceramic
- Aggregate all data on-chain via subgraph, aggregate profile data via ceramic, host via IPFS using `eth.limo`

These should be taken into consideration for anything remotely usable as an explorer across our testnets. For now, since testnets had been slowed to prioritize stability and other apps, alongside any analytics for rewards are currently being exported from Dune, this is moved to `icebox`.
