### ISSUE TITLE
Prepare HOPR testnet on xDAI chain

### ISSUE THREAD

**Issue by QYuQianchen** [hoprnet/hopr-devrel#58]
Our next testnet will take place on xDAI chain. This means that when you pull the next release of HOPR protocol and run it on your PC with the updated instruction, the blockchain part (`HoprChannels` and `HoprToken` smart contracts) of the HOPR protocol runs on xDAI chain. We created one DuneAnalytics dashboard that uses blockchain events to analyse testnet participation. As DuneAnalytics' queries and dashboard are chain-specific, we need to create a new dashboard for the upcoming testnet on xDAI.
# Dashboard
## Queries on xDAI
- [x] #64
- [x] #59

## New query on Polygon
- [x] #60

## Last modification
When the testnet contract gets deployed on xDAI
- [x] #67
- [x] Fork the withdraw query for xDAI
- [x] #61
- [x] Make the [xDAI testnet dashboard](https://dune.xyz/hoprnet/HOPR-xDAI-Testnet-Wildhorn-v2) public

# Airdrop `tHOPR`
- [x] #68

# Mint NFT
- [x] Prepare a MM wallet
- [x] #62

**Comment by Eleonora0119** [comment]
Batchmint ready by 07/11/2021
